routes/web.php
<?php

Route::middleware('auth')->group(function() {

    Route::get('/', function () {
        return view('welcome');
    });

    //----- Rutas Erick -----//
    Route::resource('empleado', 'EmpleadoController');
    Route::resource('genero', 'GeneroController');
    Route::resource('profesion', 'ProfesionController');
    Route::resource('estadocivil', 'EstadoCivilController');
    // prueba dinamico

    Route::get('/','WelcomeController@welcome');
    Route::resource('puestos','PuestosTrabajoController');
    Route::resource('descuentos','DescuentoController');
    Route::resource('ingresos','IngresoController');
    Route::resource('comisiones','ComisionController');
    Route::resource('rentas','RentaController');
    Route::get('puestos-puesto-nombres','PuestosResumenController@nombres');
    Route::get('puestos-puesto-rango-salario','PuestosResumenController@rangoSalario');
    Route::get('puestos-puesto-cuenta', 'PuestosResumenController@cuenta');
    Route::get('Empleado/chiefsEmployees/{id}','EmpleadoController@showChiefsEmployees');
    Route::get('SelectPais/{id}','EmpleadoController@getAllRegiones');
    Route::get('SelectRegion/{id}','EmpleadoController@getAllSubRegiones');

    Route::resource('planillas','PlanillaController');
    Route::resource('config','ConfiguracionController');
    Route::resource('ad-empresa', 'AdministracionEmpresaController');
    
    //Rutas de Milton
    Route::resource('empresa','EmpresaController');
    Route::resource('unidad-organizativa','UnidadOrganizativaController');    
    Route::resource('centro-costos','CentroCostosController');
    Route::post('unidad-organizativa/insert', 'UnidadOrganizativaController@insert')->name('unidad-organizativa.insert');
    Route::post('unidad-organizativa/save', 'UnidadOrganizativaController@save')->name('unidad-organizativa.save');
    Route::get('unidad-organizativa/{id}/subunidades', 'UnidadOrganizativaController@subunidades')->name('unidad-organizativa.subunidades');
    Route::delete('centro-costos/remove', 'CentroCostosController@remove')->name('centro-costos.remove');

    // Lineas nuevas del la rama de Luis >>>>>>> luis
    Route::get('get-departamentos-planilla', 'PlanillaHelperController@getDepartamentos');
    Route::get('get-sub-unidades-planilla', 'PlanillaHelperController@getSubUnidades');
    Route::get('get-empleados-planilla', 'PlanillaHelperController@getUnidadEmpleados');

    Route::get('get-planilla-ingresos', 'PlanillaHelperController@getPlanillaIngresos');
    Route::get('get-planilla-descuentos', 'PlanillaHelperController@getPlanillaDescuentos');
    Route::get('get-planilla-comisiones', 'PlanillaHelperController@getPlanillaComisiones');

    Route::post('planilla-seleccionar-unidades','PlanillaProcessController@unidades');
    Route::post('planilla-seleccionar-empleados','PlanillaProcessController@nuevaPlanilla');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-reporte-empleados/{numero}','PlanillaProcessController@planillaPdf');

    Route::get('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@agregarIngresoPlanilla');
    Route::post('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@guardarIngresoPlanilla');

    Route::get('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@agregarDescuentoPlanilla');
    Route::post('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@guardarDescuentoPlanilla');

    Route::get('planilla-nuevo-comision/{planilla}','PlanillaProcessController@agregarComisionPlanilla');
    Route::post('planilla-nuevo-comision/{planilla}','PlanillaProcessController@guardarComisionPlanilla');

    Route::get('planilla-editar/{planilla}','PlanillaProcessController@editarPlanillas');
    Route::post('planilla-actualizar/{planilla}','PlanillaProcessController@actualizarPlanillas');

    Route::get('planilla-centros-costos','PlanillaProcessController@getCentrosAfectados');

    Route::get('eliminar-planilla-{planilla}-ingreso-{ingreso}','PlanillaProcessController@eliminarPlanillaIngreso');
    Route::get('eliminar-planilla-{planilla}-descuento-{descuento}','PlanillaProcessController@eliminarPlanillaDescuento');
    Route::get('eliminar-planilla-{planilla}-comision-{comision}','PlanillaProcessController@eliminarPlanillaComision');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');




Route::get('/info', 'HomeController@info');
Route::group(['middleware' =>  ['auth','admin']], function () {
      Route::resource('usuarios', 'HomeController'); 
      Route::get('usuarios/{id}','HomeController@edituser');
      Route::get('usuarios/{id}','HomeController@updateuser');
      Route::get('bitacora','HomeController@bitacora');
});

Route::get('generate-pdf','PlanillaReportController@testReport');

Route::get('get-regiones','DireccionController@getRegiones');

app/Renta.php
<?php

namespace bab115g9;

use Illuminate\Database\Eloquent\Model;

class Renta extends Model
{
    protected $table = 'Rentas';

    protected $fillable = [
        'tramo',
        'desde',
        'hasta',
        'porcentaje',
        'sobreExceso',
        'cuotaFija',
        'retencion'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function descuentos()
    {
        return $this->hasMany('App\Descuento');
    }
}

app/Http/Controllers/RentaController.php
<?php

namespace bab115g9\Http\Controllers;

use bab115g9\Renta;
use Illuminate\Http\Request;

class RentaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rentas = Renta::all();
        return view('renta.index', compact('rentas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('renta.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateRenta($request);
        $renta = new Renta([
            'tramo' => $request->get('tramo'),
            'desde' => $request->get('desde'),
            'hasta' => $request->get('hasta'),
            'porcentaje' => $request->exists('porcentaje') ? $request->get('porcentaje'): 0.00,
            'sobreExceso' => $request->exists('sobreExceso') ? $request->get('sobreExceso'): 0.00,
            'cuotaFija' => $request->get('cuotaFija') ? $request->get('cuotaFija'): 0.00,
            'retencion' => $request->get('retencion')
            ]);
        $renta->save();
        return redirect('/rentas')->with('message','Nueva Renta guardada correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $renta = Renta::find($id);
        return view('renta.show',compact('renta'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $renta = Renta::find($id);
        return view('renta.edit', compact('renta'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validateRenta($request);
        $renta = Renta::find($id);
        $renta->tramo = $request->get('tramo');
        $renta->desde = $request->get('desde');
        $renta->hasta = $request->get('hasta');
        $renta->porcentaje = $request->exists('porcentaje') ? $request->get('porcentaje'): 0.00;
        $renta->cuotaFija = $request->exists('sobreExceso') ? $request->get('sobreExceso'): 0.00;
        $renta->retencion = $request->get('retencion');
        $renta->save();

        return redirect('/rentas')->with('message','Renta editada correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $renta = Renta::find($id);
        $renta->delete();

        return redirect('/rentas')->with('message','Renta eliminada correctamente.');
    }

    private function validateRenta($request)
    {
        $request->validate([
           'tramo'=>'required',
           'desde'=>'required',
           'hasta'=>'required',
           'retencion'=>'required'
        ]);
    }
}

resources/views/renta/edit.blade.php
@extends('layouts.appForm')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('rentas.index')}}"><i class="material-icons">list</i> Tabla de renta</a></li>
            <li class="active"><i class="material-icons">archive</i> Editar renta</li>
        </ol>
    </div>
    @if ($errors->any())
        <div id="alert-panel">
            <div class="alert alert-danger">
                <h4><i class="material-icons">error</i> Se encontraron los siguientes errores</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Formulario para editar tramo en tabla de renta
                    </h2>
                    <small>La tabla de retención debe estar en concordancia con la presentada por el ministerio de hacienda</small>
                </div>
                <div class="body masked-input">
                    <form id="main" class="form-horizontal" method="post" action="{{route('rentas.update', $renta->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="tramo">Tramo</label>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="number" id="tramo" name="tramo" class="form-control" max="100" min="1" value="{{$renta->tramo}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="desde">Desde ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="desde" name="desde" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{$renta->desde}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="hasta">Hasta ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="hasta" name="hasta" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{$renta->hasta }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="aplicaRetencion">Aplicar retención</label>
                            </div>
                            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                <div class="switch">
                                    <input class="filled-in" type="checkbox" id="aplicaRetencion" name="aplicaRetencion" value="aplicaRetencion" checked>
                                    <input class="form-control hidden" value="{{$renta->retencion}}" type="text" id="retencion" name="retencion">
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="porcentaje">Porcentaje a aplicar (%)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="porcentaje" name="porcentaje" class="form-control porcent valor-retenido" placeholder="Eje: 5.00 %" value="{{$renta->porcentaje}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="sobreExceso">Sobre el exceso de ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="sobreExceso" name="sobreExceso" class="form-control money-dollar valor-retenido" placeholder="Eje: 99,99 $" value="{{$renta->sobreExceso}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="cuotaFija">Más cuota fija de ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="cuotaFija" name="cuotaFija" class="form-control money-dollar valor-retenido" placeholder="Eje: 99,99 $" value="{{$renta->cuotaFija}}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Actualizar</button>
                                <a href="{{route('rentas.index')}}" type="button" class="btn btn-secondary m-t-15 waves-effect">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $("#main").validate({
            rules: {
                tramo:{
                    required:true,
                    number:true,
                    range: [1,100]
                },
                hasta:{
                    number:true,
                    greaterThan: "#desde"
                },
                desde:{
                    number:true,
                    smallerThan: "#hasta"
                },
                porcentaje:{
                    required: true,
                    number:true
                },
                sobreExceso: {
                    required:true,
                    number:true
                },
                cuotaFija:{
                    required:true,
                    number:true
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.form-group').append(error);
            }
        });
        $("#aplicaRetencion").on("change", function () {
            var valoresRetenidos = $(".valor-retenido");
            if ($(this).is(':checked')){
                valoresRetenidos.removeAttr("disabled");
                $("#retencion").val(true);
            } else {
                valoresRetenidos.attr("disabled","");
                valoresRetenidos.val("0.00");
                $("#retencion").val(false);
            }
        })
    </script>
@endsection

resources/views/renta/index.blade.php
@extends('layouts.appTable')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li class="active"><i class="material-icons">archive</i> Renta</li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tablas de retención del impuesto sobre la renta
                    </h2>
                    <small>La tabla de retención debe estar en concordancia con la presentada por el ministerio de hacienda</small>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{route('rentas.create')}}"><i class="material-icons">add</i> Nuevo</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-striped table-hover js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Tramo</th>
                                <th>Desde</th>
                                <th>Hasta</th>
                                <th>% a aplicar</th>
                                <th>Sobre el exceso de</th>
                                <th>Más cuota fija de</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rentas as $renta)
                                <tr>
                                    <td>TRAMO {{$renta->tramo}}</td>
                                    <td>$ {{$renta->desde}}</td>
                                    <td>$ {{$renta->hasta}}</td>
                                    @if($renta->retencion)
                                        <td>{{$renta->porcentaje}} %</td>
                                        <td>$ {{$renta->sobreExceso}}</td>
                                        <td>$ {{$renta->cuotaFija}}</td>
                                    @else
                                        <td class="text-center">SIN RETENCIÓN</td>
                                        <td class="text-center">SIN RETENCIÓN</td>
                                        <td class="text-center">SIN RETENCIÓN</td>
                                    @endif
                                    <td>
                                        <ul class="list-unstyled">
                                            <li class="dropdown">
                                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                    <i class="material-icons">more_vert</i>
                                                </a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li>{{ method_field('get') }}<a href="{{ route('rentas.show',$renta->id) }}"><i class="material-icons">details</i> Detalles</a></li>
                                                    <li><a href="{{ route('rentas.edit', $renta->id) }}"><i class="material-icons">edit</i> Editar</a></li>
                                                    <li><a href="javascript:" class="deleteBtn" data-name="{{ $renta->tramo }}" data-id="{{ $renta->id }}"><i class="material-icons">delete</i> Eliminar</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="delete-form" method="post" action="javascript:">
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Eliminar de la retención</h4>
                    </div>
                    <div class="modal-body">
                        Se eliminara el tramo <strong id="to-delete-name"></strong>
                        <p>¿Desea continuar?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger waves-effect">Eliminar</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $(document).on('click','.deleteBtn',function () {
            var id = $(this).data('id');
            var name = $(this).data('name');
            $("#to-delete-name").text(name);
            $("#delete-form").attr('action',window.location.href + '/' + id);
            $("#deleteModal").modal("show");
        });

        $(document).on('click','.showInfo',function (e) {
            e.preventDefault();
            var url = $(this).attr("href");
            var result = $.ajax(url)
                .done(function (data) {
                    $(".modal-body #info-name .info-text").text(data.nombre);
                    $(".modal-body #info-tasa .info-text").text(data.taza);
                    $(".modal-body #info-created .info-text").text(data.created_at);
                    $(".modal-body #info-updated .info-text").text(data.updated_at);
                }).fail(function () {
                    $("#info-panel").append('<div class="alert alert-danger alert-dismissable" role="alert"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button> No se puede obtener la información del servidor, intente denuevo más tarde.</div>')
                });
            $("#infoModal").modal('show');
        });
    </script>
@endsection

resources/views/renta/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('rentas.index')}}"><i class="material-icons">list</i> Tabla de retenciones</a></li>
            <li class="active"><i class="material-icons">archive</i> Información</li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Información del Tramo {{$renta->tramo}}
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{route('rentas.edit',$renta->id)}}"><i class="material-icons">edit</i> Editar</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Desde</h4>
                            <p class="list-group-item-text">$ {{ $renta->desde }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Hasta</h4>
                            <p class="list-group-item-text">$ {{ $renta->hasta }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Porcentaje a aplicar</h4>
                            <p class="list-group-item-text">% {{ $renta->porcentaje }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Sobre el exceso de</h4>
                            <p class="list-group-item-text">$ {{ $renta->sobreExceso }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Más cuota fija de</h4>
                            <p class="list-group-item-text">{{ $renta->cuotaFija }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Ultima modificación</h4>
                            <p class="list-group-item-text">{{ $renta->updated_at->format('Y-M-d H:i:s') }}</p>
                        </div>
                    </div>
                    <div class="row clearfix p-l-15">
                        <div class="btn-group">
                            <a role="button" href="{{ route('rentas.index') }}" class="btn btn-secondary"><i class="material-icons">reply</i> Volver</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection