routes/web.php
<?php

Route::middleware('auth')->group(function() {

    Route::get('/', function () {
        return view('welcome');
    });

    //----- Rutas Erick -----//
    Route::resource('empleado', 'EmpleadoController');
    Route::resource('genero', 'GeneroController');
    Route::resource('profesion', 'ProfesionController');
    Route::resource('estadocivil', 'EstadoCivilController');
    // prueba dinamico

    Route::get('/','WelcomeController@welcome');
    Route::resource('puestos','PuestosTrabajoController');
    Route::resource('descuentos','DescuentoController');
    Route::resource('ingresos','IngresoController');
    Route::resource('comisiones','ComisionController');
    Route::resource('rentas','RentaController');
    Route::get('puestos-puesto-nombres','PuestosResumenController@nombres');
    Route::get('puestos-puesto-rango-salario','PuestosResumenController@rangoSalario');
    Route::get('puestos-puesto-cuenta', 'PuestosResumenController@cuenta');
    Route::get('Empleado/chiefsEmployees/{id}','EmpleadoController@showChiefsEmployees');
    Route::get('SelectPais/{id}','EmpleadoController@getAllRegiones');
    Route::get('SelectRegion/{id}','EmpleadoController@getAllSubRegiones');

    Route::resource('planillas','PlanillaController');
    Route::resource('config','ConfiguracionController');
    Route::resource('ad-empresa', 'AdministracionEmpresaController');
    
    //Rutas de Milton
    Route::resource('empresa','EmpresaController');
    Route::resource('unidad-organizativa','UnidadOrganizativaController');    
    Route::resource('centro-costos','CentroCostosController');
    Route::post('unidad-organizativa/insert', 'UnidadOrganizativaController@insert')->name('unidad-organizativa.insert');
    Route::post('unidad-organizativa/save', 'UnidadOrganizativaController@save')->name('unidad-organizativa.save');
    Route::get('unidad-organizativa/{id}/subunidades', 'UnidadOrganizativaController@subunidades')->name('unidad-organizativa.subunidades');
    Route::delete('centro-costos/remove', 'CentroCostosController@remove')->name('centro-costos.remove');

    // Lineas nuevas del la rama de Luis >>>>>>> luis
    Route::get('get-departamentos-planilla', 'PlanillaHelperController@getDepartamentos');
    Route::get('get-sub-unidades-planilla', 'PlanillaHelperController@getSubUnidades');
    Route::get('get-empleados-planilla', 'PlanillaHelperController@getUnidadEmpleados');

    Route::get('get-planilla-ingresos', 'PlanillaHelperController@getPlanillaIngresos');
    Route::get('get-planilla-descuentos', 'PlanillaHelperController@getPlanillaDescuentos');
    Route::get('get-planilla-comisiones', 'PlanillaHelperController@getPlanillaComisiones');

    Route::post('planilla-seleccionar-unidades','PlanillaProcessController@unidades');
    Route::post('planilla-seleccionar-empleados','PlanillaProcessController@nuevaPlanilla');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-reporte-empleados/{numero}','PlanillaProcessController@planillaPdf');

    Route::get('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@agregarIngresoPlanilla');
    Route::post('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@guardarIngresoPlanilla');

    Route::get('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@agregarDescuentoPlanilla');
    Route::post('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@guardarDescuentoPlanilla');

    Route::get('planilla-nuevo-comision/{planilla}','PlanillaProcessController@agregarComisionPlanilla');
    Route::post('planilla-nuevo-comision/{planilla}','PlanillaProcessController@guardarComisionPlanilla');

    Route::get('planilla-editar/{planilla}','PlanillaProcessController@editarPlanillas');
    Route::post('planilla-actualizar/{planilla}','PlanillaProcessController@actualizarPlanillas');

    Route::get('planilla-centros-costos','PlanillaProcessController@getCentrosAfectados');

    Route::get('eliminar-planilla-{planilla}-ingreso-{ingreso}','PlanillaProcessController@eliminarPlanillaIngreso');
    Route::get('eliminar-planilla-{planilla}-descuento-{descuento}','PlanillaProcessController@eliminarPlanillaDescuento');
    Route::get('eliminar-planilla-{planilla}-comision-{comision}','PlanillaProcessController@eliminarPlanillaComision');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');




Route::get('/info', 'HomeController@info');
Route::group(['middleware' =>  ['auth','admin']], function () {
      Route::resource('usuarios', 'HomeController'); 
      Route::get('usuarios/{id}','HomeController@edituser');
      Route::get('usuarios/{id}','HomeController@updateuser');
      Route::get('bitacora','HomeController@bitacora');
});

Route::get('generate-pdf','PlanillaReportController@testReport');

Route::get('get-regiones','DireccionController@getRegiones');

resources/views/puesto/edit.blade.php
@extends('layouts.appForm')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('puestos.index')}}"><i class="material-icons">list</i> Puestos de trabajo</a></li>
            <li class="active"><i class="material-icons">archive</i> Editar puesto</li>
        </ol>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <h4><i class="material-icons">error</i> Se encontraron los siguientes errores</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Formulario para editar puesto de trabajo
                    </h2>
                </div>
                <div class="body masked-input">
                    <form id="main" class="form-horizontal" method="post" action="{{route('puestos.update',$puesto->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="nombre">Nombre del puesto</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="nombre" name="nombre" class="form-control" value="{{ $puesto->nombre }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="descripcion">Descripción</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <textarea id="descripcion" name="descripcion" class="form-control" placeholder="Breve descripción" rows="5" >{{ $puesto->descripcion }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="salarioMaximo">Salario Máximo ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input id="salarioMaximo" type="text" name="salarioMaximo" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{ $puesto->salarioMaximo }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="salarioMinimo">Salario Mínimo ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="salarioMinimo" name="salarioMinimo" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{ $puesto->salarioMinimo }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Actualizar</button>
                                <a href="{{route('puestos.index')}}" type="button" class="btn btn-secondary m-t-15 waves-effect">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $("#main").validate({
            rules: {
                nombre:{
                    required:true,
                    maxlength:50
                },
                descripcion:{
                    maxlength:250
                },
                salarioMaximo:{
                    number:true,
                    greaterThan: "#salarioMinimo"
                },
                salarioMinimo:{
                    number:true,
                    smallerThan: "#salarioMaximo"
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endsection

resources/views/puesto/home.blade.php
@extends('layouts.appTable')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li class="active"><i class="material-icons">archive</i> Puestos de trabajo</li>
        </ol>
    </div>
    @if(session()->get('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Registros de puestos de trabajo
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{route('puestos.create')}}"><i class="material-icons">add</i> Nuevo</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-striped table-hover js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th>Salario Mayor</th>
                                <th>Salario Menor</th>
                                <th>Actualizado</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($puestos as $puesto)
                                <tr>
                                    <td>{{$puesto->nombre}}</td>
                                    <td>{{$puesto->descripcion}}</td>
                                    <td>$ {{$puesto->salarioMaximo}}</td>
                                    <td>$ {{$puesto->salarioMinimo}}</td>
                                    <td>{{$puesto->updated_at->format('Y-M-d')}}</td>
                                    <td>
                                        <ul class="list-unstyled">
                                            <li class="dropdown">
                                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                    <i class="material-icons">more_vert</i>
                                                </a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li>{{ method_field('get') }}<a href="{{ route('puestos.show',$puesto->id) }}"><i class="material-icons">details</i> Detalles</a></li>
                                                    <li><a href="{{ route('puestos.edit', $puesto->id) }}"><i class="material-icons">edit</i> Editar</a></li>
                                                    <li><a href="javascript:" class="deleteBtn" data-name="{{ $puesto->nombre }}" data-id="{{ $puesto->id }}"><i class="material-icons">delete</i> Eliminar</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="delete-form" method="post" action="javascript:">
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Eliminar puesto de trabajo</h4>
                    </div>
                    <div class="modal-body">
                        Se eliminara el puesto de <strong id="to-delete-name"></strong>
                        <p>¿Desea continuar?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger waves-effect">Eliminar</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script>
        $(".deleteBtn").on('click',function () {
            var id = $(this).data('id');
            var name = $(this).data('name');
            $("#to-delete-name").text(name);
            $("#delete-form").attr('action',window.location.href + '/' + id);
            $("#deleteModal").modal("show");
        });
    </script>
@endsection

resources/views/puesto/new.blade.php
@extends('layouts.appForm')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('puestos.index')}}"><i class="material-icons">list</i> Puestos de trabajo</a></li>
            <li class="active"><i class="material-icons">archive</i> Nuevo puesto</li>
        </ol>
    </div>
    @if ($errors->any())
        <div id="">
            <div class="alert alert-danger">
                <h4><i class="material-icons">error</i> Se encontraron los siguientes errores</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Formulario para nuevo puesto de trabajo
                    </h2>
                </div>
                <div class="body masked-input">
                    <form id="main" class="form-horizontal" method="post" action="{{route('puestos.store')}}">
                        {{ csrf_field() }}
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="nombre">Nombre del puesto</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="nombre" name="nombre" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="descripcion">Descripción</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <textarea id="descripcion" name="descripcion" class="form-control" placeholder="Breve descripción" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="salarioMaximo">Salario Máximo ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="salarioMaximo" name="salarioMaximo" class="form-control money-dollar" placeholder="Eje: 99,99 $">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="salarioMinimo">Salario Mínimo ($)</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="salarioMinimo" name="salarioMinimo" class="form-control money-dollar" placeholder="Eje: 99,99 $">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Guardar</button>
                                <a href="{{route('puestos.index')}}" type="button" class="btn btn-secondary m-t-15 waves-effect">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $("#main").validate({
            rules: {
                nombre:{
                    required:true,
                    maxlength:50
                },
                descripcion:{
                    maxlength:250
                },
                salarioMaximo:{
                    number:true,
                    greaterThan: "#salarioMinimo"
                },
                salarioMinimo:{
                    number:true,
                    smallerThan: "#salarioMaximo"
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endsection

resources/views/puesto/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('puestos.index')}}"><i class="material-icons">list</i> Puestos de trabajo</a></li>
            <li class="active"><i class="material-icons">archive</i> Información</li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Información de puestos de trabajo
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{route('puestos.edit',$puesto->id)}}"><i class="material-icons">edit</i> Editar</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Nombre del puesto de trabajo</h4>
                            <p class="list-group-item-text">{{ $puesto->nombre }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Descripción</h4>
                            <p class="list-group-item-text">{{ $puesto->descripcion }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Salario Máximo</h4>
                            <p class="list-group-item-text">$ {{ $puesto->salarioMaximo }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Salario Mínimo</h4>
                            <p class="list-group-item-text">$ {{ $puesto->salarioMinimo }}</p>
                        </div>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">Ultima modificación</h4>
                            <p class="list-group-item-text">{{ $puesto->updated_at->format('Y-M-d H:i:s') }}</p>
                        </div>
                    </div>
                    <div class="row clearfix p-l-15">
                        <div class="btn-group">
                            <a role="button" href="{{ route('puestos.index') }}" class="btn btn-secondary"><i class="material-icons">reply</i> Volver</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection