routes/web.php
<?php

Route::middleware('auth')->group(function() {

    Route::get('/', function () {
        return view('welcome');
    });

    //----- Rutas Erick -----//
    Route::resource('empleado', 'EmpleadoController');
    Route::resource('genero', 'GeneroController');
    Route::resource('profesion', 'ProfesionController');
    Route::resource('estadocivil', 'EstadoCivilController');
    // prueba dinamico

    Route::get('/','WelcomeController@welcome');
    Route::resource('puestos','PuestosTrabajoController');
    Route::resource('descuentos','DescuentoController');
    Route::resource('ingresos','IngresoController');
    Route::resource('comisiones','ComisionController');
    Route::resource('rentas','RentaController');
    Route::get('puestos-puesto-nombres','PuestosResumenController@nombres');
    Route::get('puestos-puesto-rango-salario','PuestosResumenController@rangoSalario');
    Route::get('puestos-puesto-cuenta', 'PuestosResumenController@cuenta');
    Route::get('Empleado/chiefsEmployees/{id}','EmpleadoController@showChiefsEmployees');
    Route::get('SelectPais/{id}','EmpleadoController@getAllRegiones');
    Route::get('SelectRegion/{id}','EmpleadoController@getAllSubRegiones');

    Route::resource('planillas','PlanillaController');
    Route::resource('config','ConfiguracionController');
    Route::resource('ad-empresa', 'AdministracionEmpresaController');
    
    //Rutas de Milton
    Route::resource('empresa','EmpresaController');
    Route::resource('unidad-organizativa','UnidadOrganizativaController');    
    Route::resource('centro-costos','CentroCostosController');
    Route::post('unidad-organizativa/insert', 'UnidadOrganizativaController@insert')->name('unidad-organizativa.insert');
    Route::post('unidad-organizativa/save', 'UnidadOrganizativaController@save')->name('unidad-organizativa.save');
    Route::get('unidad-organizativa/{id}/subunidades', 'UnidadOrganizativaController@subunidades')->name('unidad-organizativa.subunidades');
    Route::delete('centro-costos/remove', 'CentroCostosController@remove')->name('centro-costos.remove');

    // Lineas nuevas del la rama de Luis >>>>>>> luis
    Route::get('get-departamentos-planilla', 'PlanillaHelperController@getDepartamentos');
    Route::get('get-sub-unidades-planilla', 'PlanillaHelperController@getSubUnidades');
    Route::get('get-empleados-planilla', 'PlanillaHelperController@getUnidadEmpleados');

    Route::get('get-planilla-ingresos', 'PlanillaHelperController@getPlanillaIngresos');
    Route::get('get-planilla-descuentos', 'PlanillaHelperController@getPlanillaDescuentos');
    Route::get('get-planilla-comisiones', 'PlanillaHelperController@getPlanillaComisiones');

    Route::post('planilla-seleccionar-unidades','PlanillaProcessController@unidades');
    Route::post('planilla-seleccionar-empleados','PlanillaProcessController@nuevaPlanilla');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-modificar-empleados/{numero}','PlanillaProcessController@mostrarEmpleados');

    Route::get('planilla-reporte-empleados/{numero}','PlanillaProcessController@planillaPdf');

    Route::get('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@agregarIngresoPlanilla');
    Route::post('planilla-nuevo-ingreso/{planilla}','PlanillaProcessController@guardarIngresoPlanilla');

    Route::get('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@agregarDescuentoPlanilla');
    Route::post('planilla-nuevo-descuento/{planilla}','PlanillaProcessController@guardarDescuentoPlanilla');

    Route::get('planilla-nuevo-comision/{planilla}','PlanillaProcessController@agregarComisionPlanilla');
    Route::post('planilla-nuevo-comision/{planilla}','PlanillaProcessController@guardarComisionPlanilla');

    Route::get('planilla-editar/{planilla}','PlanillaProcessController@editarPlanillas');
    Route::post('planilla-actualizar/{planilla}','PlanillaProcessController@actualizarPlanillas');

    Route::get('planilla-centros-costos','PlanillaProcessController@getCentrosAfectados');

    Route::get('eliminar-planilla-{planilla}-ingreso-{ingreso}','PlanillaProcessController@eliminarPlanillaIngreso');
    Route::get('eliminar-planilla-{planilla}-descuento-{descuento}','PlanillaProcessController@eliminarPlanillaDescuento');
    Route::get('eliminar-planilla-{planilla}-comision-{comision}','PlanillaProcessController@eliminarPlanillaComision');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');




Route::get('/info', 'HomeController@info');
Route::group(['middleware' =>  ['auth','admin']], function () {
      Route::resource('usuarios', 'HomeController'); 
      Route::get('usuarios/{id}','HomeController@edituser');
      Route::get('usuarios/{id}','HomeController@updateuser');
      Route::get('bitacora','HomeController@bitacora');
});

Route::get('generate-pdf','PlanillaReportController@testReport');

Route::get('get-regiones','DireccionController@getRegiones');

app/Comision.php
<?php

namespace bab115g9;

use Illuminate\Database\Eloquent\Model;

class Comision extends Model
{
    protected $table = 'Comisiones';

    protected $fillable = ['nombre','valorMenor','valorMayor','taza'];
}

app/Http/Controllers/ComisionController.php
<?php

namespace bab115g9\Http\Controllers;

use bab115g9\Comision;
use Illuminate\Http\Request;

class ComisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comisiones = Comision::all();
        return view('comision.index', compact('comisiones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('comision.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateComision($request);
        $request->validate(['nombre'=>'unique:Comisiones']);
        $comision = new Comision([
           'nombre' => $request->get('nombre'),
           'valorMenor' => $request->get('valorMenor'),
           'valorMayor' => $request->get('valorMayor'),
           'taza' => $request->get('taza')
        ]);
        $comision->save();
        return redirect('/comisiones')->with('message', 'La comisión fue guardada correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $comision = Comision::find($id);
        return $comision;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comision = Comision::find($id);
        return view('comision.edit', compact('comision'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validateComision($request);
        $comision = Comision::find($id);
        $comision->nombre = $request->get('nombre');
        $comision->valorMenor = $request->get('valorMenor');
        $comision->valorMayor = $request->get('valorMayor');
        $comision->taza = $request->get('taza');
        $comision->save();
        return redirect('/comisiones')->with('message','Comisión actualizada correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comision = Comision::find($id);
        $comision->delete();
        return redirect('comisiones/')->with('message', 'Comisión eliminada correctamente.');
    }

    public function validateComision($request)
    {
        $request->validate([
           'nombre'=>'required|max:50',
           'valorMenor'=>'required|regex:/^\d+(\.\d{1,2})?$/',
           'valorMayor'=>'required|regex:/^\d+(\.\d{1,2})?$/',
           'taza'=>'required|regex:/^\d+(\.\d{1,2})?$/'
        ]);
    }
}

resources/views/comision/edit.blade.php
@extends('layouts.appForm')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('comisiones.index')}}"><i class="material-icons">list</i> Comisiones</a></li>
                <li class="active"><i class="material-icons">archive</i> Editar comisión</li>
        </ol>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <h4><i class="material-icons">error</i> Se encontraron los siguientes errores</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Formulario para editar comisión
                    </h2>
                </div>
                <div class="body masked-input">
                    <form id="main" class="form-horizontal" method="post" action="{{route('comisiones.update', $comision->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="nombre">Nombre de la comisión</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="nombre" name="nombre" class="form-control" value="{{ $comision->nombre }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="taza">Tasa</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="taza" name="taza" class="form-control porcent" placeholder="Eje: 10.00 %" value="{{ $comision->taza }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="valorMayor">Valor Máximo</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="valorMayor" name="valorMayor" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{ $comision->valorMayor }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="valorMenor">Valor Mínimo</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="valorMenor" name="valorMenor" class="form-control money-dollar" placeholder="Eje: 99,99 $" value="{{ $comision->valorMenor }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Actualizar</button>
                                <a href="{{route('comisiones.index')}}" type="button" class="btn btn-secondary m-t-15 waves-effect">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $( "#main" ).validate({
            rules: {
                nombre: {
                    required: true,
                    maxlength:50
                },
                taza: {
                    required: true,
                    number: true,
                    range: [0,100]
                },
                valorMayor: {
                    required: true,
                    greaterThan: "#valorMenor"
                },
                valorMenor: {
                    required: true,
                    smallerThan: "#valorMayor"
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endsection

resources/views/comision/index.blade.php
@extends('layouts.appTable')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li class="active"><i class="material-icons">archive</i> Comisión</li>
        </ol>
    </div>
    @if(session()->get('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Registros de comisiones aplicables a planillas de empleados
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{route('comisiones.create')}}"><i class="material-icons">add</i> Nuevo</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-striped table-hover js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Valor Mayor</th>
                                <th>Valor Menor</th>
                                <th>Tasa</th>
                                <th>Editado</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($comisiones as $comision)
                                <tr>
                                    <td>{{ $comision->nombre }}</td>
                                    <td>$ {{ $comision->valorMayor }}</td>
                                    <td>$ {{ $comision->valorMenor }}</td>
                                    <td>{{ $comision->taza }} %</td>
                                    <td> {{ $comision->updated_at->format('Y-M-d') }}</td>
                                    <td>
                                        <ul class="list-unstyled">
                                            <li class="dropdown">
                                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                    <i class="material-icons">more_vert</i>
                                                </a>
                                                <ul class="dropdown-menu pull-right">
                                                    <li><a href="{{ route('comisiones.show',$comision->id) }}" class="showInfo"><i class="material-icons">details</i> Detalles</a></li>
                                                    <li><a href="{{ route('comisiones.edit', $comision->id) }}"><i class="material-icons">edit</i> Editar</a></li>
                                                    <li><a href="javascript:" class="deleteBtn" data-name="{{ $comision->nombre }}" data-id="{{ $comision->id }}"><i class="material-icons">delete</i> Eliminar</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="delete-form" method="post" action="javascript:">
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Eliminar Comisión</h4>
                    </div>
                    <div class="modal-body">
                        Se eliminara la comisión <strong id="to-delete-name"></strong>
                        <p>¿Desea continuar?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger waves-effect">Eliminar</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="infoModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="infoModalLabel">Información</h4>
                </div>
                <div class="modal-body">
                    <blockquote id="info-name">
                        <p>Nombre</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                    <blockquote id="info-tasa">
                        <p>Tasa</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                    <blockquote id="info-max">
                        <p>Valor Máximo</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                    <blockquote id="info-min">
                        <p>Valor Mínimo</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                    <blockquote id="info-created">
                        <p>Fecha creación</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                    <blockquote id="info-updated">
                        <p>Ultima actualización</p>
                        <footer class="info-text"></footer>
                    </blockquote>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script>
        $(document).on('click','.deleteBtn',function () {
            var id = $(this).data('id');
            var name = $(this).data('name');
            $("#to-delete-name").text(name);
            $("#delete-form").attr('action',window.location.href + '/' + id);
            $("#deleteModal").modal("show");
        });
        $(document).on('click','.showInfo',function (e) {
            e.preventDefault();
            var url = $(this).attr("href");
            var result = $.ajax(url)
                .done(function (data) {
                    $(".modal-body #info-name .info-text").text(data.nombre);
                    $(".modal-body #info-tasa .info-text").text(data.taza);
                    $(".modal-body #info-max .info-text").text(data.valorMayor);
                    $(".modal-body #info-min .info-text").text(data.valorMenor);
                    $(".modal-body #info-created .info-text").text(data.created_at);
                    $(".modal-body #info-updated .info-text").text(data.updated_at);
                }).fail(function () {
                    $("#info-panel").append('<div class="alert alert-danger alert-dismissable" role="alert"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button> No se puede obtener la información del servidor, intente denuevo más tarde.</div>')
                });
            $("#infoModal").modal('show');
        });
    </script>
@endsection

resources/views/comision/new.blade.php
@extends('layouts.appForm')

@section('content')
    <div class="block-header">
        <ol class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="material-icons">home</i> Inicio</a></li>
            <li><a href="{{route('comisiones.index')}}"><i class="material-icons">list</i> Comisiones</a></li>
            <li class="active"><i class="material-icons">archive</i> Nueva comisión</li>
        </ol>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <h4><i class="material-icons">error</i> Se encontraron los siguientes errores</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Formulario para nueva comisión
                    </h2>
                </div>
                <div class="body masked-input">
                    <form id="main" class="form-horizontal" method="post" action="{{route('comisiones.store')}}">
                        {{ csrf_field() }}
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="nombre">Nombre de la comisión</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="nombre" name="nombre" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="taza">Tasa</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="taza" name="taza" class="form-control porcent" placeholder="Eje: 10.00 %">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="valorMayor">Valor Máximo</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="valorMayor" name="valorMayor" class="form-control money-dollar" placeholder="Eje: 99,99 $">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="valorMenor">Valor Mínimo</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="valorMenor" name="valorMenor" class="form-control money-dollar" placeholder="Eje: 99,99 $">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Guardar</button>
                                <a href="{{route('comisiones.index')}}" type="button" class="btn btn-secondary m-t-15 waves-effect">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script>
        $( "#main" ).validate({
            rules: {
                nombre: {
                    required: true,
                    maxlength:50
                },
                taza: {
                    required: true,
                    number: true,
                    range: [0,100]
                },
                valorMayor: {
                    required: true,
                    greaterThan: "#valorMenor"
                },
                valorMenor: {
                    required: true,
                    smallerThan: "#valorMayor"
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endsection